import { notFound } from "next/navigation";
import { query } from "@/lib/db";
import AuditTimeline from "../../AuditTimeline";

/* ----------------------------------
   TYPES
----------------------------------- */
type VersionRow = {
    version: number;
    markdown_path: string;
    created_by: "ai" | "human";
    change_summary: string | null;
    created_at: string;
};

/* ----------------------------------
   PAGE
----------------------------------- */
export default async function AuditPage({
    params,
}: {
    params: Promise<{ id: string }>;
}) {
    const { id: conceptId } = await params;

    /* -------- Audit Events -------- */
    const auditEvents = (await query(
        `
  SELECT event_type, actor_role, details, created_at
  FROM audit_events
  WHERE concept_id = $1
  ORDER BY created_at DESC
  `,
        [conceptId]
    )).map((e: any) => ({
        ...e,
        created_at_formatted: new Date(e.created_at).toLocaleString(
            "en-IN",
            { hour12: true }
        ),
    }));

    /* -------- Version History -------- */
    const versions: VersionRow[] = await query(
        `
    SELECT
      version,
      markdown_path,
      created_by,
      change_summary,
      created_at
    FROM concept_versions
    WHERE concept_id = $1
    ORDER BY version DESC
    `,
        [conceptId]
    );

    if (!auditEvents) notFound();

    return (
        <div className="min-h-screen bg-gray-50 px-8 py-24">
            <div className="mx-auto max-w-5xl space-y-6">

                {/* ===============================
            HEADER
        ================================ */}
                <div className="rounded-xl bg-white p-6 shadow-sm">
                    <h1 className="text-2xl font-semibold">
                        Admin Audit & Version History
                    </h1>
                    <p className="mt-1 text-sm text-gray-500">
                        Internal review history for this concept
                    </p>
                </div>

                {/* ===============================
            VERSION HISTORY
        ================================ */}
                <div className="rounded-xl bg-white p-6 shadow-sm">
                    <h2 className="mb-4 text-lg font-semibold">
                        Version History
                    </h2>

                    {versions.length === 0 ? (
                        <p className="text-sm text-gray-500">
                            No versions recorded yet.
                        </p>
                    ) : (
                        <ul className="space-y-3 text-sm">
                            {versions.map((v) => (
                                <li
                                    key={v.version}
                                    className="flex items-start justify-between rounded-md border p-3"
                                >
                                    <div>
                                        <div className="font-medium">
                                            Version v{v.version}
                                        </div>

                                        <div className="text-xs text-gray-500">
                                            {v.created_by === "ai"
                                                ? "Generated by AI"
                                                : "Published by Human"}
                                            {" · "}
                                            {new Date(v.created_at).toLocaleString()}
                                        </div>

                                        {v.change_summary && (
                                            <p className="mt-1 text-xs text-gray-600">
                                                {v.change_summary}
                                            </p>
                                        )}
                                    </div>

                                    <div className="text-xs text-gray-400 text-right">
                                        {v.markdown_path}
                                    </div>
                                </li>
                            ))}
                        </ul>
                    )}
                </div>

                {/* ===============================
            AUDIT TIMELINE
        ================================ */}
                <div className="rounded-xl bg-white p-6 shadow-sm">
                    <h2 className="mb-4 text-lg font-semibold">
                        Audit Timeline
                    </h2>

                    <AuditTimeline events={auditEvents} />
                </div>

            </div>
        </div>
    );
}